### ISSUE TITLE
64 bit support missing

### ISSUE THREAD

**Issue by abhijeetkmr** [adam-roth/coredata-threadsafe#4]
Now appstore has made strict rules that only 64bit supported apps only could be submitted or updated in appstore. 
So i upgraded my app but got one error in IAThreadsafe. It doesnot support 64bit.
![image](https://cloud.githubusercontent.com/assets/5485721/7977214/7dfc2858-0aa5-11e5-9bba-c0c298ab15a6.png)

There is no way for us to make changes into this.

**Comment by adam-roth** [comment]
Hi abhijeet, the code should work just fine in a 64-bit application if you include the sources directly.  

There might be issues if you're building the project as a Universal Framework and then including that framework in your 64-bit project.  However, for issues relating to that you should probably raise a ticket over at:

https://github.com/kstenerud/iOS-Universal-Framework

Whether or not the Universal Framework will work in a 64-bit project depends upon the tool used to build it (i.e. the project linked above).  The project sources themselves don't care what architecture they're being compiled for.

**Comment by abhijeetkmr** [comment]
Thank you so much for getting in touch.
Yeah i have been using the IAthreadsafe.framework which is not supported for 64 bit. 
So sir, Should I be using the source files instead of framework now (as framework is not supported and i need a fix ).

**Comment by adam-roth** [comment]
Yes, for now the simplest workaround is to use the sources instead of the framework.

**Comment by abhijeetkmr** [comment]
Thanks sir,
Will get back to you on this.
